<?php 

/**
 * Joomla! 1.5 component supplyorder
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_supplyorder
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


function com_install()
  {
  ?>
<div class="header">Supplyorder is sucessfully installed </div>
<p>
A component built to handle supply order requests for Joomla 1.5.
</p>
<?php
  }
?>